export default {
    AUTH_SIGNUP:"AUTH_SIGNUP",
    AUTH_LOGIN: 'AUTH_LOGIN',
    AUTH_LOGOUT: 'AUTH_LOGOUT',
    AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR',
    AUTH_SIGNUP_ERROR:"AUTH_SIGNUP_ERROR",
    ERROR_GENERIC: 'ERROR_GENERIC',
    REFRESH_TOKEN: 'REFRESH_TOKEN',


    LOAD_ALL_QUIZ: 'LOAD_ALL_QUIZ',
    ACTIVE_QUIZ: 'ACTIVE_QUIZ',
    SCORE_QUIZ:'SCORE_QUIZ',
    TOTAL_SCORE: 'TOTAL_SCORE',
    
    UPDATE_USER:'UPDATE_USER',

    USERS_LOAD:'USERS_LOAD',

  
    LOAD_ALL_USERS: 'LOAD_ALL_USERS'

  };
  