export default {
    LOAD_ALL_QUIZ: 'LOAD_ALL_QUIZ',
    ACTIVE_QUIZ: 'ACTIVE_QUIZ',
    SCORE_QUIZ:'SCORE_QUIZ',
    TOTAL_SCORE: 'TOTAL_SCORE',
    AUTH_LOGIN: 'AUTH_LOGIN',
    AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR',
    
    AUTH_LOGOUT: 'AUTH_LOGOUT',
    USERS_LOAD:'USERS_LOAD',

    AUTH_SIGNUP:"AUTH_SIGNUP",
    AUTH_SIGNUP_ERROR:"AUTH_SIGNUP_ERROR",

    ERROR_GENERIC: 'ERROR_GENERIC',


  };
  